id: 1
domains:
  - "localhost"
  - "pingora"
locations:
  - path: "/static/"
    matchType: "prefix"
    type: "static"
    staticDir: "/public"
  - path: "/"
    matchType: "prefix"
    type: "proxy"
    balanceMethod: "round_robin"
    upstreams:
      - server: "172.30.0.10"
        port: 3000
        weight: 1
enabled: true
hsts: false
http2: false
