id: 1
domains:
  - "localhost"
  - "pingora"
upstreams:
  - server: "172.30.0.10"
    port: 3000
    weight: 1
balance_method: "round_robin"
locations:
  - path: "/static/"
    matchType: "prefix"
    type: "static"
    staticDir: "/public"
  - path: "/"
    matchType: "prefix"
    type: "proxy"
enabled: true
hsts: false
http2: false
